
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class GiaoDienC extends javax.swing.JFrame {

    ArrayList<sachs> list = new ArrayList<>();
    int current = 0;
    String userName = "sa";
    String password = "hanh789";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QLTV_BT";
    private DefaultTableModel tableModel;
    private int stt;

    /**
     * Creates new form GiaoDienC
     */
    public GiaoDienC() {
        initComponents();
        LoadDataToArray();
        LoadDataArrayListToTable();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachs = new javax.swing.JTable();
        btnlamMoi = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btncapNhat = new javax.swing.JButton();
        btnTroLai = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtmaSach = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttenSach = new javax.swing.JTextField();
        txttheLoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttacGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsoLuong = new javax.swing.JTextField();
        txttinhTrang = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rdoTheoMS = new javax.swing.JRadioButton();
        rdoTheoTS = new javax.swing.JRadioButton();
        rdoTheoTG = new javax.swing.JRadioButton();
        txtTim = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÍ SÁCH");

        tblSachs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Tác giả", "Số lượng", "Tình trạng"
            }
        ));
        tblSachs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSachs);

        btnlamMoi.setText("Làm mới");
        btnlamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlamMoiActionPerformed(evt);
            }
        });

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btncapNhat.setText("Cập Nhật");
        btncapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapNhatActionPerformed(evt);
            }
        });

        btnTroLai.setText("Trở lại");
        btnTroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroLaiActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã sách:");

        jLabel3.setText("Tên sách:");

        txttheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttheLoaiActionPerformed(evt);
            }
        });

        jLabel4.setText("Thể loại:");

        jLabel7.setText("Tình trạng:");

        jLabel5.setText("Tác giả:");

        jLabel6.setText("Số lượng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(txttenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(txtmaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsoLuong)
                            .addComponent(txttinhTrang))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txttacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txttinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(68, 68, 68))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("tìm kiếm"));

        buttonGroup1.add(rdoTheoMS);
        rdoTheoMS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdoTheoMS.setText("Theo Mã Sách");

        buttonGroup1.add(rdoTheoTS);
        rdoTheoTS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdoTheoTS.setText("Theo Tên Sách");

        buttonGroup1.add(rdoTheoTG);
        rdoTheoTG.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rdoTheoTG.setText("Theo Tác Giả");
        rdoTheoTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTheoTGActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdoTheoTS, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(rdoTheoTG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem))
                    .addComponent(rdoTheoMS, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rdoTheoMS)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTheoTS)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoTheoTG)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jButton1.setText("All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnlamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnxoa)
                        .addGap(18, 18, 18)
                        .addComponent(btncapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnTroLai)
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlamMoi)
                    .addComponent(btnluu)
                    .addComponent(btnxoa)
                    .addComponent(btncapNhat)
                    .addComponent(btnTroLai)
                    .addComponent(btnThoat)
                    .addComponent(jButton1))
                .addGap(294, 294, 294))
        );

        jTabbedPane1.addTab("Sách", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean checktrung(String ma) {
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).MaSach.equalsIgnoreCase(ma)) {
                return true;
            }
        }
        return false;
    }
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(); // để ghi thông báo nếu để rỗng giá trị hoặc không chọn
        if (txtmaSach.getText().isBlank()) {
            sb.append("Bạn cần nhập mã sách\n");
        }
        if (txttenSach.getText().isBlank()) {
            sb.append("Bạn cần nhập tên sách\n");
        }
        if (txttacGia.getText().isBlank()) {
            sb.append("Bạn cần nhập tác giả sách\n");
        }
        if (txttheLoai.getText().isBlank()) {
            sb.append("Bạn cần nhập thể loại sách\n");
        }
        if (txttinhTrang.getText().isBlank()) {
            sb.append("Bạn cần nhập tình trạng sách\n");
        }
        if (txtsoLuong.getText().isBlank()) {
            sb.append("Bạn cần nhập số lượng sách\n");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(null, sb);//nếu sb(đoạn cảnh báo) có độ dài thì xuất hiện bảng loại messa có câu cảnh báo
        } else {
            if (checktrung(txtmaSach.getText()) == true) {
                JOptionPane.showMessageDialog(this, "Mã sách bị trùng");
            } else {
                int row = 0;
                try {

                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection conn = DriverManager.getConnection(url, userName, password);
                    String sql = "insert into QLSACH values (?,?,?,?,?,?)";
                    PreparedStatement st = conn.prepareStatement(sql);
                    st.setString(1, txtmaSach.getText());
                    st.setString(2, txttenSach.getText());
                    st.setString(3, txttheLoai.getText());
                    st.setString(4, txttacGia.getText());
                    st.setString(5, txtsoLuong.getText());
                    st.setString(6, txttinhTrang.getText());

                    row = st.executeUpdate();
                    if (row > 0) {

                        JOptionPane.showMessageDialog(this, "Lưu thành công");
                    } else {
                        JOptionPane.showMessageDialog(this, "Trùng mã sách");
                    }
                    conn.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi");
                    System.out.println(e);
                }
            }
        }
        LoadDataToArray();
        LoadDataArrayListToTable();
    }//GEN-LAST:event_btnluuActionPerformed

    private void btncapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapNhatActionPerformed
        // TODO add your handling code here:
        if (txtmaSach.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập mã sách");
            txtmaSach.requestFocus();
            return;
        }
        try {
            int row = 0;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection(url, userName, password);
            String sql = "update QLSACH set TenSach=?, TheLoai=?, TacGia=?, SoLuong=?, TinhTrang=? where MaSach=?";
            PreparedStatement st = conn.prepareStatement(sql);

            st.setString(1, txttenSach.getText());
            st.setString(2, txttheLoai.getText());
            st.setString(3, txttacGia.getText());
            st.setString(4, txtsoLuong.getText());
            st.setString(5, txttinhTrang.getText());
            st.setString(6, txtmaSach.getText());
            row = st.executeUpdate();
            if (row > 0) {

                JOptionPane.showMessageDialog(this, "Cập nhât thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Mã sách không đúng");
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi");
            System.out.println(e);
        }
        LoadDataToArray();
        LoadDataArrayListToTable();
    }//GEN-LAST:event_btncapNhatActionPerformed

    private void tblSachsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachsMouseClicked
        // TODO add your handling code here:
        int r = tblSachs.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblSachs.getModel();

        String maSach = (String) model.getValueAt(r, 0);
        String tenSach = (String) model.getValueAt(r, 1);
        String theLoai = (String) model.getValueAt(r, 2);

        String tacGia = (String) model.getValueAt(r, 3);
        String soLuong = (String) model.getValueAt(r, 4);
        String tinhTrang = (String) model.getValueAt(r, 5);

        txtmaSach.setText(maSach);
        txttenSach.setText(tenSach);
        txttheLoai.setText(theLoai);
        txttacGia.setText(tacGia);
        txtsoLuong.setText(soLuong);
        txttinhTrang.setText(tinhTrang);

    }//GEN-LAST:event_tblSachsMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (txtmaSach.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập mã sách");
            txtmaSach.requestFocus();
        }
        try {
            int row = 0;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection(url, userName, password);
            String sql = "delete from QLSACH where MaSach = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, txtmaSach.getText());

            row = st.executeUpdate();
            if (row > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Mã sách không đúng");
            }
            xoatrang();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi");
            System.out.println(e);
        }
        LoadDataToArray();
        LoadDataArrayListToTable();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void xoatrang() {

        txtmaSach.setText("");
        txttenSach.setText("");
        txttheLoai.setText("");
        txttacGia.setText("");
        txtsoLuong.setText("");
        txttinhTrang.setText("");

    }
    private void btnlamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlamMoiActionPerformed
        // TODO add your handling code here:
        txtmaSach.setText("");
        txttenSach.setText("");
        txttheLoai.setText("");
        txttacGia.setText("");
        txtsoLuong.setText("");
        txttinhTrang.setText("");
    }//GEN-LAST:event_btnlamMoiActionPerformed


    private void btnTroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroLaiActionPerformed
        // TODO add your handling code here:
        new MenuChinh().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTroLaiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    
    private void LoadDataToArray() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection conn = DriverManager.getConnection(url, userName, password);
            Statement stm = (Statement) conn.createStatement();
            String sql = "select * from QLSACH";
            ResultSet rs = stm.executeQuery(sql);
            list.clear();
            while (rs.next()) {
                String maSach = rs.getString(1);
                String tenSach = rs.getString(2);
                String theloai = rs.getString(3);
                String tacGia = rs.getString(4);
                String soluong = rs.getString(5);
                String tinhtrang = rs.getString(6);

                sachs sach = new sachs(maSach, tenSach, tacGia, theloai, soluong, tinhtrang);
                list.add(sach);
            }
            conn.close();
        } catch (Exception e) {
            System.out.println("Ket noi that bai");
            System.out.println(e);
        }
    }

    private void LoadDataArrayListToTable() {
        DefaultTableModel model = (DefaultTableModel) tblSachs.getModel();
        model.setRowCount(0);

        for (sachs s : list) {
            model.addRow(new Object[]{s.getMaSach(), s.getTenSach(), s.getTheLoai(), s.getTacGia(), s.getSoLuong(), s.getTinhTrang()});
        }
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        var timK = txtTim.getText();
        if(!timK.isEmpty()){
            if(rdoTheoMS.isSelected()){
                timtheoMaSach();
            }else if(rdoTheoTS.isSelected()){
                timtheoTenSach();
            }else{
                timtheoTacGia();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "ô tìm kiếm đang rỗng!");
        }
          
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void timtheoMaSach() {
        String maSach = txtTim.getText();
        DefaultTableModel model = (DefaultTableModel) tblSachs.getModel();
        model.setRowCount(0);
        boolean tim = false;

        for (sachs book : list) {
            if (book.getMaSach().toLowerCase().contains(maSach.toLowerCase())) {
                model.addRow(new Object[]{book.getMaSach(), book.getTenSach(), book.getTheLoai(), book.getTacGia(), book.getSoLuong(), book.getTinhTrang()});
                tim = true;
            }
        }
        if (!tim) {
            JOptionPane.showMessageDialog(this, "Mã sách khong tồn tại");
        }
    }
    private void timtheoTenSach(){
        String tenSachCanTim = txtTim.getText();
        DefaultTableModel model = (DefaultTableModel) tblSachs.getModel();
        model.setRowCount(0);
        boolean tim = false;// Xóa dữ liệu trong bảng trước khi hiển thị kết quả tìm kiếm
        for (sachs s : list) {
            if (s.getTenSach().toLowerCase().contains(tenSachCanTim.toLowerCase())) {
                model.addRow(new Object[]{s.getMaSach(), s.getTenSach(), s.getTheLoai(), s.getTacGia(), s.getSoLuong(), s.getTinhTrang()});
                tim = true;
            }
        }
        if (!tim) {
            JOptionPane.showMessageDialog(this, "Tên sách khong tồn tại");
        }
    }
    private void timtheoTacGia(){
        String tacGiaCanTim = txtTim.getText();
        DefaultTableModel model = (DefaultTableModel) tblSachs.getModel();
        model.setRowCount(0);
        boolean tim = false;// Xóa dữ liệu trong bảng trước khi hiển thị kết quả tìm kiếm
        for (sachs s : list) {
            if (s.getTacGia().toLowerCase().contains(tacGiaCanTim.toLowerCase())) {
                model.addRow(new Object[]{s.getMaSach(), s.getTenSach(), s.getTheLoai(), s.getTacGia(), s.getSoLuong(), s.getTinhTrang()});
                tim = true;
            }
        }
        if (!tim) {
            JOptionPane.showMessageDialog(this, "Tác giả sách khong tồn tại");
        }
    }
    
//    private void timSach(String tenSachCanTim) {
//        String tenSachCanTim = txtTim.getText();
//        DefaultTableModel model = (DefaultTableModel) tblSachs.getModel();
//        model.setRowCount(0); // Xóa dữ liệu hiện có trong bảng
//
//        for (sachs book : list) {
//            if (book.getTenSach().equalsIgnoreCase(tenSachCanTim)) {
//                // Hiển thị sách tìm thấy trong bảng
//                model.addRow(new Object[]{book.getMaSach(), book.getTenSach(), book.getTheLoai(), book.getTacGia(), book.getSoLuong(), book.getTinhTrang()});
//            }
//        }
//    }
    private void txttheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttheLoaiActionPerformed

    private void rdoTheoTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTheoTGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTheoTGActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoadDataArrayListToTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    
//    public ArrayList<sachs> searchByName (ArrayList<sachs> listDG,
//            String nameStudent) {
//        ArrayList<sachs> listSearch = new ArrayList<>();
//         for (var e : listDG) {
//             var name = e.getTenSach().split("\\s+");
//             var firstName = name[name.length-1];
//            if(firstName.equalsIgnoreCase(nameStudent)) {
//                listSearch.add(e);
//            } 
//        }
//         return listSearch;
//    }
//    private void showSearchStudent(sachs e) {
//        int stt = 1;
//        tableModel.setRowCount(0);
////        docgiaModal dg = list.get(current);
////        boolean gt = dg.gioiTinh;
////        if (gt == true) {
////            rdoNu.setSelected(true);
////        } else {
////            rdoNam.setSelected(true);
////        }
//        var row = new Object[]{stt++, e.getMaSach(), e.getTenSach(),
//            e.getTheLoai(), e.getTacGia(), e.getSoLuong(),e.getTinhTrang()
//            };
//        tableModel.addRow(row);
//        tableModel.fireTableDataChanged();
//    }
//    
//    private void showListSeachStudent(ArrayList<sachs> listSearch) {
//        int stt = 1;
//        tableModel.setRowCount(0);
//        for (var e : listSearch) {
//            var row = new Object[]{stt++, e.getMaSach(), e.getTenSach(),
//            e.getTheLoai(), e.getTacGia(), e.getSoLuong(),e.getTinhTrang()};
//            tableModel.addRow(row);
//            tableModel.fireTableDataChanged();
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTroLai;
    private javax.swing.JButton btncapNhat;
    private javax.swing.JButton btnlamMoi;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdoTheoMS;
    private javax.swing.JRadioButton rdoTheoTG;
    private javax.swing.JRadioButton rdoTheoTS;
    private javax.swing.JTable tblSachs;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtmaSach;
    private javax.swing.JTextField txtsoLuong;
    private javax.swing.JTextField txttacGia;
    private javax.swing.JTextField txttenSach;
    private javax.swing.JTextField txttheLoai;
    private javax.swing.JTextField txttinhTrang;
    // End of variables declaration//GEN-END:variables

}
